config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'
  resources :categories
  resources :cards

  get 'new_review_session', to: 'cards#new_review_session', as: 'new_review_session'
  get 'next_card', to: 'cards#next_card', as: 'next_card'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :category
  has_one :flip_side, class_name: "Card"

  validates :description, presence: true, length: { minimum: 1 }
  validates :category_id, presence: true

  def self.get_cards_by_category(category = nil)
    category.present? ? Card.where("category_id = ?", category) : Card.all
  end

  def self.get_review_cards(category)
    get_cards_by_category(category).where("front = true")
  end

  def self.save_cards(front, back)
    front.save
    back.flip_side_id = front.id
    back.save
    front.update!(flip_side_id: back.id)
  end

  def delete
    Card.destroy(self.flip_side_id)
    self.destroy
  end

  def keep_flip_category_in_sync
    Card.find(self.flip_side_id).update(category_id: self.category_id)
  end

  def update_streak(correct)
    correct == "true" ? self.streak += 1 : self.streak = 0
    self.save
    keep_streak_in_sync
  end

  def keep_streak_in_sync
    Card.find(self.flip_side_id).update(streak: self.streak)
  end
end

app/models/card_result.rb
class CardResult < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :cards
  validates :description, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
before_action :get_categories, only: [:index, :new, :edit]

  def index
    @category = params[:category]
    @cards = Card.get_cards_by_category(@category)

    respond_to do |format|
      format.html
      format.json { render json: @cards }
    end
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
  end

  def create
    front  = Card.new(description: card_params[:front], category_id: card_params[:category_id], front: 1)
    back   = Card.new(description: card_params[:back], category_id: card_params[:category_id], back: 1)

    if front.valid? && back.valid?
      Card.save_cards(front, back)
      redirect_to root_path
    else
      flash[:error] = "Oops something went wrong! Try again"
      redirect_to :back
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    card = Card.find(params[:id])
    if card.update(card_params)
      card.keep_flip_category_in_sync
      flash[:success] = "Card Updated!"
    else
      flash[:error] = "Oops something went wrong! Card not updated"
    end
    redirect_to cards_path
  end

  def destroy
    card = Card.find(params[:id])
    card.delete
    redirect_to cards_path
  end

  def new_review_session
    review_cards = Card.get_review_cards(params[:category]).shuffle
    session[:index] = 0
    review_card(review_cards)
  end

  def next_card
    last_card = Card.find(params[:card])
    last_card.update_streak(params[:correct])

    session[:index] += 1

    return redirect_to cards_path if end_of_session
    review_card(params[:review_cards])
  end

  def review_card(review_cards)
    @review_cards = review_cards
    @front = Card.find(@review_cards[session[:index]])
    @back = Card.find(@front.flip_side_id)
    render :review_card
  end

  def end_of_session
    session[:index] >= params[:review_cards].length
  end

  private

  def card_params
    params.require(:card).permit(:category_id, :front, :back, :id, :description )
  end

  def get_categories
    @categories = Category.all
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
  end

  def create
    @category = Category.new(category_params)
    if @category.valid?
      @category.save
      flash[:success] = 'Category created!'
    else
      flash[:error] = 'Oops something went wrong! Try again'
    end
    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:description)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_card_header(side, index)
    return unless index == 0
    "<h2>#{ side }</h2>".html_safe
  end

  def category_select_value
    params[:category] ? params[:category][:category_id] : 0
  end

  def find_card(cards, card_id)
    cards.find{|card| card.id == card_id }
  end

  def display_card(card)
    streak = card.streak >= 10 ? 10 : card.streak
    "<div class='card streak-#{ streak }'>
      #{ card.description.html_safe }
      </div>".html_safe
  end
end

app/views/cards/edit.html.erb
<div class="new_card_form">
  <%= form_for @card, url: { action: "update" }, method: "patch" do |f| %>
    <div class="field">
      <%= f.hidden_field :id, value: @card.id %>

      <%= f.label :category_id, "Category" %>
      <%= f.collection_select(:category_id, @categories, :id, :description, {}, {class: "form-control dropdown"} ) %><br/>

      <%= f.label :description, "Description" %>
      <%= f.text_area :description, rows: 10, width: "100%", class: "form-control"  %><br/>

      <%= f.submit "Update Card", class: "btn btn-primary submit" %>
    </div>
  <% end %>
</div>

app/views/cards/index.html.erb
<div class="review-cards">
  <%= form_for :category, url: { action: "index", remote: true }, html: { method: "GET" }, enforce_utf8: false do |f| %>
    <div class="field">
      <%= f.label :category, "Category", class: "sr-only" %>
      <%= f.collection_select(:category_id, @categories, :id, :description, { :include_blank => "All Cards", :selected => category_select_value }, {class: "form-control"} ) %><br>

      <%= link_to new_review_session_path( :category => @category ), id: "review-cards-btn"  do %>
        <button class="btn btn-success form-control">Review These Cards</button>
      <% end %>
    </div>
  <% end %>
</div>

<div class="display_cards">
  <% @cards.each_with_index do |card, i| %>
    <% next unless card.front %>
    <div class="front-cards">
      <%= display_card_header("Front", i) %>
      <%= display_card(card) %>
      <button class="btn btn-primary edit-delete"><%= link_to "Edit", edit_card_path(card.id) %></button>
      <button class="btn btn-danger edit-delete"><%= link_to "Delete", card, method: :delete, data: { confirm: "Are you sure?" } %></button>
    </div>

    <div class="back-cards">
      <%= display_card_header("Back", i) %>
      <%= display_card(find_card(@cards, card.flip_side_id)) %>
      <button class="btn btn-primary edit-delete"><%= link_to "Edit", edit_card_path(card.flip_side_id) %></button>
      <button class="btn btn-danger edit-delete"><%= link_to "Delete", card, method: :delete, data: { confirm: "Are you sure?" } %></button>
    </div>

  <% end %>
</div>

app/views/cards/new.html.erb
<div class="new_card_form">
  <%= form_for :card, url: { action: "create" } do |f| %>
    <div class="field">
      <%= f.label :category_id, "Category" %>
      <%= f.collection_select(:category_id, @categories, :id, :description, {}, {class: "form-control dropdown"} ) %><br/>

      <%= f.label :front, "Front of Card" %>
      <%= f.text_area :front, rows: 10, width: "100%", class: "form-control"  %><br/>

      <%= f.label :back, "Back of Card" %>
      <%= f.text_area :back, rows: 10, width: "100%", class: "form-control" %><br/>

      <%= f.submit "Add Card", class: "btn btn-primary submit" %>
    </div>
  <% end %>
</div>

app/views/cards/review_card.html.erb
<div class="review-card">
  <div "front-cards">
    <%= render :template => "cards/show", :locals => {card: @front } %>
  </div>

  <br><br>
  <button class="btn btn-success flip-button">Flip Me</button>

  <br><br>

  <div class="back-cards">
    <%= render :template => "cards/show", :locals => {card: @back } %>
    <div class="container-fluid">
      <div class="row result-btns">
        <div class="col-xs-6 col-xs-offset-3">
          <%= link_to next_card_path(review_cards: @review_cards, correct: true, card: @front )  do %>
            <button class="btn btn-success form-control result-btn">Right!</button>
          <% end %>
          <%= link_to next_card_path(review_cards: @review_cards, correct: false, card: @front )  do %>
            <button class="btn btn-warning form-control result-btn">Wrong!</button>
          <% end %>
        </div>
      </div>
    </div>
    </div>
</div>

app/views/cards/show.html.erb
<div class="container-fluid">
  <div class="row">
    <h4><%= card.category.description %></h4>
    <div class="col-xs-6 col-xs-offset-3">
      <div class="card"><%= card.description.html_safe %></div>
      <button class="btn btn-primary edit-delete"><%= link_to "Edit", edit_card_path(card.id) %></button>
      <button class="btn btn-danger edit-delete"><%= link_to "Delete", card, method: :delete, data: { confirm: "Are you sure?" } %></button>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<%= form_for :category, url: { action: "create" } do |f| %>
  <div class="field">
    <%= f.label :description, "New Category" %>
    <%= f.text_field :description, width: "90%", class: "form-control" %><br>

    <%= f.submit "Add Category", class: "btn btn-primary submit" %>
  </div>
<% end %>

app/views/flash_cards/new_category.html.erb
<%= form_for :category, url: create_category_path do |f| %>
  <div class="field">
    <%= f.label :description, "Category" %>
    <%= f.text_field :description %>

    <%= f.submit "Add Category" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="header">
  <nav class="navbar navbar-fixed-top navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <li class="navbar-brand"><%= link_to 'Flash Cards', root_path %></li>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'New Card', new_card_path %></li>
          <li><%= link_to 'Study Cards', cards_path %></li>
          <li><%= link_to 'New Category', new_category_path %></li>
          <li><a href="https://github.com/fdel15/flash-cards" target="_blank">GitHub</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashCards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class="content">
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/static_pages/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12 col-xs-offset-1 col-sm-offset-3 col-md-offset-0">
      <div class="actions">
         <%= link_to new_card_path do %>
            <h4 class="card">Add Card</h4>
          <% end %>
        <p class="help-text">Learn something new? Make a card for it to review
        later!</p>
      </div>
    </div>
    <div class="col-md-4 col-sm-6 col-xs-12 col-xs-offset-1 col-sm-offset-3 col-md-offset-0">
      <div class="actions">
        <%= link_to cards_path do %>
          <h4 class="card">Review Cards</h4>
        <% end %>
        <p class="help-text">View and edit any card you have already created.</p>
      </div>
    </div>
    <div class="col-md-4 col-sm-6 col-xs-12 col-xs-offset-1 col-sm-offset-3 col-md-offset-0">
      <div class="actions">
        <%= link_to new_category_path do %>
          <h4 class="card">Add Category</h4>
        <% end %>
        <p class="help-text">Tackling a new topic? Create a new category to assign cards to!</p>
      </div>
    </div>
  </div>
</div>